FROM python:3.10-slim

WORKDIR /app

COPY client/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "client/client.py", "--hospital-id", "hospital_a", "--data-path", "data/hospital_a.csv"]